# Generated by Django 5.0.1 on 2024-01-26 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.TextField(verbose_name='Примечание')),
                ('defect_status', models.CharField(choices=[('CR', 'Критично'), ('WA', 'Предупреждение'), ('CO', 'Без замечаний')], default='CO', max_length=2, verbose_name='Статус примечания')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('key', models.CharField(max_length=500, verbose_name='Держатель ключей')),
                ('document', models.CharField(max_length=500, verbose_name='Держатель документов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата закрытия')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.car', verbose_name='Автомобиль')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.city', verbose_name='Город')),
                ('photo', models.ManyToManyField(to='manual.photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Отчеты по автомобилям',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CarMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Временный владелец')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.car', verbose_name='Автомобиль')),
                ('daily_check', models.ManyToManyField(to='management.dailycheck', verbose_name='Смены')),
            ],
            options={
                'verbose_name_plural': 'Транзакции автомобилей',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='dailycheck',
            index=models.Index(fields=['active', 'author'], name='management__active_317dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='carmigration',
            index=models.Index(fields=['active', 'author'], name='management__active_0506cf_idx'),
        ),
    ]
