# Generated by Django 5.0.1 on 2024-01-30 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('manual', '0003_alter_car_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheck',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='dailycheck',
            name='defect',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='dailycheck',
            name='mileage',
            field=models.PositiveIntegerField(null=True, verbose_name='Пробег'),
        ),
    ]
