# Generated by Django 5.0.1 on 2024-01-26 13:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
            ],
            options={
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.carmark', verbose_name='Марка')),
            ],
            options={
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gos_number', models.CharField(max_length=9, verbose_name='Гос. номер')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('slug', models.SlugField(max_length=9, verbose_name='SLUG-ссылка')),
                ('year', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2024)], verbose_name='Год выпуска')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.carmodel', verbose_name='Марка/Модель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.DateField(verbose_name='Страховка')),
                ('technical_service', models.PositiveIntegerField(verbose_name='ТО')),
                ('grm', models.PositiveIntegerField(verbose_name='ГРМ')),
                ('status', models.CharField(choices=[('JO', 'В работе'), ('FR', 'Свободен'), ('RE', 'Зарезервирован'), ('TS', 'На ТО')], default='FR', max_length=2, verbose_name='Статус')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manual.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name_plural': 'Автомобиль. Дополнительные сведения',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('photo', models.ImageField(upload_to='profile_images', verbose_name='Фото')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.car', verbose_name='Автомобиль')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.city', verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
