# Generated by Django 5.0.1 on 2024-01-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_alter_car_managers_alter_carparam_car'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='car',
            managers=[
            ],
        ),
    ]
